python build_dp.py --data_path='../data/Vertebrata/Test Files' &&
python build_dp.py --data_path='../data/Fish/Test Files/Actinopterygii' &&
python build_dp.py --data_path='../data/Fish/Test Files/Neopterygii' &&
python build_dp.py --data_path='../data/Fish/Test Files/Ostariophysi' &&
python build_dp.py --data_path='../data/Fish/Test Files/Cypriniformes' &&
python build_dp.py --data_path='../data/Fish/Test Files/Cyprinidae' &&
python build_dp.py --data_path='../data/Bacteria/Test_Files' &&
python build_dp.py --data_path='../data/Bacteria/Proteo_Test_Files' &&
python build_dp.py --data_path='../data/Influenza-A/Test Files' &&
python build_dp.py --data_path='../data/Dengue/Test Files' 
python build_dp.py --data_path='../data/HBV/Test Files'
