#python get_pairs.py --data_path='data/Vertebrata/Vertebrata.p' --k=6 --modify='noise' --output='data/Vertebrata/noise_testing_data.p'
#python get_pairs.py --data_path='data/Vertebrata/Vertebrata.p' --k=6 --modify='mutate' --output='data/Vertebrata/testing_data.p'
#python get_pairs.py --data_path='data/Vertebrata_Balanced/Vertebrata_Balanced.p' --k=6 --modify='noise' --output='data/Vertebrata_Balanced/noise_testing_data.p'
#python get_pairs.py --data_path='data/Vertebrata_Balanced/Vertebrata_Balanced.p' --k=6 --modify='mutation' --output='data/Vertebrata_Balanced/testing_data.p'
#python get_pairs.py --data_path='data/Influenza/Influenza.p' --k=6 --modify='noise' --output='data/Influenza/noise_testing_data.p'
#python get_pairs.py --data_path='data/Influenza/Influenza.p' --k=6 --modify='mutation' --output='data/Influenza/testing_data.p'
python get_pairs.py --data_path='data/Influenza_Balanced/Influenza_Balanced.p' --k=6 --modify='noise' --output='data/Influenza_Balanced/noise_testing_data.p'
#python get_pairs.py --data_path='data/Influenza_Balanced/Influenza_Balanced.p' --k=6 --modify='mutation' --output='data/Influenza_Balanced/testing_data.p'
python $SOURCEDIR/Hyperparameter_Search.py --data_dir=/home/pmillana/scratch/data/Vertebrata_Balanced --out_dir=/home/pmillana/scratch/data/Vertebrata_Balanced --modify='noise'
python $SOURCEDIR/Hyperparameter_Search.py --data_dir=/home/pmillana/scratch/data/Vertebrata_Balanced --out_dir=/home/pmillana/scratch/data/Vertebrata_Balanced --modify='mutation'
python $SOURCEDIR/Hyperparameter_Search.py --data_dir=/home/pmillana/scratch/data/Influenza_Balanced --out_dir=/home/pmillana/scratch/data/Influenza_Balanced --modify='mutation'
